export const REGISTER_USER="REGISTER_USER";
export const LOGIN_USER="LOGIN_USER";
export const LOGOUT_USER="LOGOUT_USER";
export const CHANGE_LOGIN="CHANGE_LOGIN";
export const DOUBLECHECKED_ID="DOUBLECHECKED_ID";
export const SET_HEADER= "SET_HEADER";
export const SET_USER_DETAIL= "SET_USER_DETAIL";
export const SET_USER_CREW = "SET_USER_CREW";
export const SET_CLICK_MARKER = "SET_CLICK_MARKER";
export const SET_CREW_DATA = "SET_CREW_DATA";
export const SET_MATCHING_DATA = "SET_MATCHING_DATA";
export const POST_MATCHING = "POST_MATCHING";
export const USER_REQUEST_MATCHING = "USER_REQUEST_MATCHING";
export const SET_LOC = "SET_LOC";

export const MATCHING_CONFIRM = "MATCHING_CONFIRM";
export const MATCHING_REFUSE = "MATCHING_REFUSE";

export const CREW_CONFIRM = "CREW_CONFIRM";
export const CREW_REFUSE = "CREW_REFUSE";
export const DEL_MATCHING = "DEL_MATCHING";
export const DEL_CREWW = "DEL_CREW";

export const REGISTER_CREW = "REGISTER_CREW";
export const REQUEST_CREW = "REQUEST_CREW";
export const DEPORT_CREW_MEMBER = "DEPORT_CREW_MEMBER";